export const FETCHING = 'FETCHING';
export const SET_GLOBAL_CURRENCY = 'SET_GLOBAL_CURRENCY';
export const SET_GLOBAL_ORDER = 'SET_GLOBAL_ORDER';
export const SET_GLOBAL_COIN = 'SET_GLOBAL_COIN';
export const SET_GLOBAL_SYMBOL = 'SET_GLOBAL_SYMBOL';
